# frozen_string_literal: true

require "minitest/autorun"
require "digest"
require "json"
require_relative "../tools/jev_format"

# Holds the Ruby port of Jev Local's rendering and its tokenization to the
# reference's own bytes.
#
# The oracle is generated by `rake oracle:jev_tokenizer`, which loads
# jev_local's `prompting.py` and the same Rust tokenizer transformers
# wraps. What this catches: a `content` that writes JSON the Python way
# (`{"a": 1, "b": 2}`, spaces after commas) but Ruby does not, and a pair
# encoding or `only_first` truncation that differs from the reference.
#
# Pure Ruby: the renderer is text and the tokenizer is a gem, so this
# needs no extension. It is not a pass when the oracle is missing
# (docs/plan.md section 12).
#
# `tokenizers` is deliberately not a dependency (section 15.58), and
# Bundler hides a gem that is not in the Gemfile, so under `bundle exec
# rake test` this skips. Run it where it can be exercised:
#
#   JEV_TOKENIZER=<...>/tokenizer.json ruby -Itest test/jev_tokenizer_test.rb
#
# It also skips without the tokenizer file, as the model parity tests do
# without their weights.
class JevTokenizerTest < Minitest::Test
  ORACLE = File.expand_path("oracle/jev-tokenizer.json", __dir__)

  def setup
    raise "#{ORACLE} is missing; run `rake oracle:jev_tokenizer`" unless File.file?(ORACLE)

    @oracle = JSON.parse(File.read(ORACLE, encoding: "UTF-8"))
    skip "tokenizers gem not installed" unless gem_available?
    skip "no tokenizer.json (set JEV_TOKENIZER)" unless tokenizer_path
  end

  def gem_available?
    require "tokenizers"
    true
  rescue LoadError
    false
  end

  # The reference's own file, or the copy the Hub cache would hold for the
  # model the oracle was recorded against.
  def tokenizer_path
    given = ENV.fetch("JEV_TOKENIZER", nil)
    return given if given && File.file?(given)

    model = @oracle.dig("tokenizer", "model").gsub("/", "--")
    Dir[File.expand_path("~/.cache/huggingface/hub/models--#{model}/snapshots/*/tokenizer.json")]
      .max_by { |path| File.mtime(path) }
  end

  def tokenizer
    @tokenizer ||= begin
      tokenizer = Tokenizers::Tokenizer.from_file(tokenizer_path)
      tokenizer.enable_truncation(@oracle.fetch("max_length"), strategy: "only_first")
      tokenizer
    end
  end

  def test_the_format_version_is_the_one_the_checkpoint_will_carry
    assert_equal Jev::FORMAT_VERSION, @oracle.fetch("format_version")
  end

  def test_the_tokenizer_is_the_one_the_reference_was_recorded_from
    assert_equal @oracle.dig("tokenizer", "sha256"),
                 Digest::SHA256.file(tokenizer_path).hexdigest,
                 "tokenizer.json is not the one the oracle was recorded from"
  end

  def test_the_rendering_is_the_reference_byte_for_byte
    @oracle.fetch("cases").each do |kase|
      assert_equal kase.fetch("context"),
                   Jev.render_context(kase.fetch("state"), kase.fetch("question")),
                   "#{kase.fetch("name")}: context"
      assert_equal kase.fetch("candidates"),
                   Jev.render_candidates(kase.fetch("choices"), kase.fetch("descriptions")),
                   "#{kase.fetch("name")}: candidates"
    end
  end

  def test_the_ids_are_the_reference_ids
    @oracle.fetch("cases").each do |kase|
      kase.fetch("input_ids").each_with_index do |expected, i|
        ids = tokenizer.encode(kase.fetch("context"), kase.fetch("candidates")[i]).ids

        assert_equal expected, ids, "#{kase.fetch("name")}: candidate #{i}"
      end
    end
  end
end
