//! mlx-c, bound here rather than through mlx-rs (notes/plan-mlxc-migration.md).
//!
//! Why: `mlx-rs` cannot be built for anything but Apple's platforms, and one
//! of the reasons is not its own. `mlx/c/half.h` defines `float16_t` and
//! `bfloat16_t` only on ARM, so `mlx_array_data_float16` and its three
//! siblings are absent from the C API on x86_64, and `mlx-rs` uses them
//! unconditionally. Teaching it not to would change its public API per
//! platform, which is not a change to ask of somebody else's crate.
//!
//! What those four do is read a half-precision value into a *host*
//! variable, which x86_64 has no type for. Computing in fp16 or bf16 is
//! untouched: the dtypes are in the enum, `mlx_astype` converts, and every
//! op takes them. The engine reads f32 and i32 across its boundary and
//! converts the rest, so it never wanted them.
//!
//! The shape of what is here is mlx-rs's, on purpose: the same names, the
//! same argument order, the same module paths under `mlxc`. Moving the
//! engine onto it is then a change of `use` lines rather than a rewrite,
//! and mlx-rs stays readable as the reference for which mlx-c variant each
//! call means (docs/vendoring.md keeps that table).

// Nothing outside the tests calls this yet: the engine moves onto it in
// one change (plan Phase 3), and this goes with that change.
#![allow(dead_code, unused_imports)]

/// mlx-c, as bindgen read its headers. Generated by build.rs from the
/// prefix that is linked, so what is declared here is what is in the
/// archive.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
pub(crate) mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

mod array;
pub mod ops;
pub mod error;
pub(crate) mod handle;
pub mod transforms;

pub use array::{Array, ArrayElement, Dtype};
