//! mlx-c, bound here rather than through mlx-rs (notes/plan-mlxc-migration.md).
//!
//! Why: `mlx-rs` cannot be built for anything but Apple's platforms, and one
//! of the reasons is not its own. `mlx/c/half.h` defines `float16_t` and
//! `bfloat16_t` only on ARM, so `mlx_array_data_float16` and its three
//! siblings are absent from the C API on x86_64, and `mlx-rs` uses them
//! unconditionally. Teaching it not to would change its public API per
//! platform, which is not a change to ask of somebody else's crate.
//!
//! What those four do is read a half-precision value into a *host*
//! variable, which x86_64 has no type for. Computing in fp16 or bf16 is
//! untouched: the dtypes are in the enum, `mlx_astype` converts, and every
//! op takes them. The engine reads f32 and i32 across its boundary and
//! converts the rest, so it never wanted them.
//!
//! **mlx-rs's names where they cost nothing; stronger types where they
//! can hold a rule.** The binding began as mlx-rs's shape exactly, which made
//! moving the engine onto it a change of `use` lines, and mlx-rs is still
//! the reference for which mlx-c variant each call means (docs/vendoring.md
//! keeps that table). With mlx-rs gone, its signatures are no longer a
//! constraint where a type can hold a rule the code would otherwise have to
//! remember: constructors return `Result`, so an [`Array`] always holds an
//! array; a draw takes its key as `&Array`; and reading a value returns
//! `Result` rather than panicking.

/// mlx-c, as bindgen read its headers. Generated by build.rs from the
/// prefix that is linked, so what is declared here is what is in the
/// archive.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
pub(crate) mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

mod array;
pub mod error;
pub mod fast;
pub(crate) mod handle;
mod io;
pub mod memory;
pub mod nn;
pub mod ops;
pub mod random;
pub mod transforms;

pub use array::{Array, ArrayElement, Dtype};
pub use ops::stop_gradient;
