//! mlx-c, bound here rather than through mlx-rs.
//!
//! This is the first slice of that move, and deliberately the riskiest one:
//! `value_and_grad` is the only place where a Rust closure is handed across
//! the C boundary, so it is the only place where a mistake compiles and then
//! misbehaves. Everything else the engine needs from mlx-rs is a call that
//! either links or does not.
//!
//! Why the move: `mlx-rs` cannot be built for anything but Apple's platforms,
//! and one of the reasons is not its own. `mlx/c/half.h` defines `float16_t`
//! and `bfloat16_t` only on ARM, so `mlx_array_data_float16` and its three
//! siblings are absent from the C API on x86_64, and `mlx-rs` uses them
//! unconditionally. Teaching it not to would change its public API per
//! platform, which is not a change to ask of somebody else's crate.
//!
//! What those four do is read a half-precision value into a *host*
//! variable, which x86_64 has no type for. Computing in fp16 or bf16 is
//! untouched: the dtypes are in the enum, `mlx_astype` converts, and every
//! op takes them. The engine reads f32 and i32 across its boundary and
//! converts the rest, so it never wanted them.

use std::cell::RefCell;
use std::ffi::{c_void, CStr};
use std::panic::{catch_unwind, AssertUnwindSafe};

use anyhow::{anyhow, Result};

/// mlx-c, as bindgen read its headers. Generated by build.rs from the prefix
/// that is linked, so what is declared here is what is in the archive.
#[allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]
mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

const SUCCESS: i32 = 0;
const FAILURE: i32 = 1;

thread_local! {
    /// What a closure failed with, on its way back through C.
    ///
    /// The boundary returns an `int`, so a Rust error cannot travel on it.
    /// It waits here instead, and the caller picks it up after mlx-c has
    /// told it that something went wrong.
    static ESCAPED: RefCell<Option<anyhow::Error>> = const { RefCell::new(None) };
}

fn park(error: anyhow::Error) {
    ESCAPED.with(|slot| *slot.borrow_mut() = Some(error));
}

fn collect() -> Option<anyhow::Error> {
    ESCAPED.with(|slot| slot.borrow_mut().take())
}

/// An `mlx_array`, freed when it goes.
pub struct Array(sys::mlx_array);

impl Array {
    /// Takes ownership of an array mlx-c has just made.
    ///
    /// # Safety
    ///
    /// The caller must own `raw`: it is freed when this is dropped.
    pub unsafe fn from_raw(raw: sys::mlx_array) -> Self {
        Self(raw)
    }

    pub fn as_raw(&self) -> sys::mlx_array {
        self.0
    }

    /// A scalar, for the tests below and for nothing else yet.
    pub fn from_f32(value: f32) -> Self {
        Self(unsafe { sys::mlx_array_new_float32(value) })
    }

    pub fn item_f32(&self) -> Result<f32> {
        let mut out = 0f32;
        let status = unsafe { sys::mlx_array_item_float32(&mut out, self.0) };
        if status == SUCCESS {
            Ok(out)
        } else {
            Err(anyhow!("mlx_array_item_float32 refused this array"))
        }
    }
}

impl Drop for Array {
    fn drop(&mut self) {
        unsafe { sys::mlx_array_free(self.0) };
    }
}

/// An `mlx_vector_array`, freed when it goes.
struct Vector(sys::mlx_vector_array);

impl Vector {
    fn of(arrays: &[Array]) -> Self {
        let raw: Vec<_> = arrays.iter().map(Array::as_raw).collect();
        Self(unsafe { sys::mlx_vector_array_new_data(raw.as_ptr(), raw.len()) })
    }

    /// The arrays inside, each one owned from here on.
    ///
    /// `mlx_vector_array_get` hands out a new reference rather than a
    /// borrow, so what comes back is the caller's to free.
    unsafe fn take(raw: sys::mlx_vector_array) -> Result<Vec<Array>> {
        let count = sys::mlx_vector_array_size(raw);
        (0..count)
            .map(|index| {
                let mut array = sys::mlx_array_new();
                let status = sys::mlx_vector_array_get(&mut array, raw, index);
                if status == SUCCESS {
                    Ok(Array::from_raw(array))
                } else {
                    sys::mlx_array_free(array);
                    Err(anyhow!("mlx_vector_array_get refused index {index}"))
                }
            })
            .collect()
    }
}

impl Drop for Vector {
    fn drop(&mut self) {
        unsafe { sys::mlx_vector_array_free(self.0) };
    }
}

/// What mlx-c calls, and what calls the Rust closure behind `payload`.
///
/// Nothing may unwind out of here: this frame is called from C++, where a
/// Rust panic is undefined behaviour rather than an error. A panic is caught,
/// parked, and reported as a failure, which is the only thing the signature
/// can say.
extern "C" fn trampoline<F>(
    out: *mut sys::mlx_vector_array,
    inputs: sys::mlx_vector_array,
    payload: *mut c_void,
) -> i32
where
    F: FnMut(&[Array]) -> Result<Vec<Array>>,
{
    let caught = catch_unwind(AssertUnwindSafe(|| unsafe {
        let closure = &mut *(payload as *mut F);
        let given = match Vector::take(inputs) {
            Ok(given) => given,
            Err(error) => {
                park(error);
                return FAILURE;
            }
        };
        match closure(&given) {
            Ok(produced) => {
                // Handing the vector over rather than dropping it: mlx-c
                // owns what it is given here.
                let vector = Vector::of(&produced);
                *out = vector.0;
                std::mem::forget(vector);
                SUCCESS
            }
            Err(error) => {
                park(error);
                FAILURE
            }
        }
    }));

    caught.unwrap_or_else(|_| {
        park(anyhow!("a closure panicked while MLX was calling it"));
        FAILURE
    })
}

extern "C" fn release<F>(payload: *mut c_void) {
    if payload.is_null() {
        return;
    }
    let _ = catch_unwind(AssertUnwindSafe(|| unsafe {
        drop(Box::from_raw(payload as *mut F));
    }));
}

/// The value of `fun` at `inputs`, and its gradients with respect to the
/// arguments `argnums` names.
///
/// One shape, because the engine has one call site (`executor.rs`). A
/// general `value_and_grad` is not wanted here: what is wanted is the one
/// the engine already asks for.
pub fn value_and_grad<F>(fun: F, argnums: &[i32], inputs: &[Array]) -> Result<(Vec<Array>, Vec<Array>)>
where
    F: FnMut(&[Array]) -> Result<Vec<Array>>,
{
    let payload = Box::into_raw(Box::new(fun)) as *mut c_void;
    // The closure owns the payload from here: mlx-c calls `release` when it
    // drops the closure, whether or not anything below succeeds.
    let closure = unsafe {
        sys::mlx_closure_new_func_payload(Some(trampoline::<F>), payload, Some(release::<F>))
    };

    let mut valued = unsafe { sys::mlx_closure_value_and_grad_new() };
    let status = unsafe {
        sys::mlx_value_and_grad(&mut valued, closure, argnums.as_ptr(), argnums.len())
    };
    if status != SUCCESS {
        unsafe {
            sys::mlx_closure_value_and_grad_free(valued);
            sys::mlx_closure_free(closure);
        }
        return Err(collect().unwrap_or_else(|| anyhow!("mlx_value_and_grad refused this closure")));
    }

    let given = Vector::of(inputs);
    let mut values = unsafe { sys::mlx_vector_array_new() };
    let mut grads = unsafe { sys::mlx_vector_array_new() };
    let status = unsafe {
        sys::mlx_closure_value_and_grad_apply(&mut values, &mut grads, valued, given.0)
    };

    let answer = if status == SUCCESS {
        unsafe { Ok((Vector::take(values)?, Vector::take(grads)?)) }
    } else {
        Err(collect().unwrap_or_else(last_error))
    };

    unsafe {
        sys::mlx_vector_array_free(values);
        sys::mlx_vector_array_free(grads);
        sys::mlx_closure_value_and_grad_free(valued);
        sys::mlx_closure_free(closure);
    }
    answer
}

/// What MLX said, when it was MLX that objected rather than the closure.
fn last_error() -> anyhow::Error {
    anyhow!("MLX refused the computation")
}

#[allow(dead_code)]
fn describe(message: *const std::os::raw::c_char) -> String {
    if message.is_null() {
        return String::new();
    }
    unsafe { CStr::from_ptr(message) }.to_string_lossy().into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::runtime;

    /// d/dx of x^2 at x = 3 is 6, and the value is 9.
    ///
    /// Trivial arithmetic on purpose: what is under test is the closure
    /// crossing into C++ and the arrays coming back, not the maths.
    #[test]
    fn a_closure_crosses_into_mlx_and_its_gradient_comes_back() {
        let answer = runtime::runtime()
            .execute(|| {
                let square = |inputs: &[Array]| -> Result<Vec<Array>> {
                    let x = inputs[0].as_raw();
                    let mut out = unsafe { sys::mlx_array_new() };
                    let stream = unsafe { sys::mlx_default_gpu_stream_new() };
                    let status = unsafe { sys::mlx_multiply(&mut out, x, x, stream) };
                    unsafe { sys::mlx_stream_free(stream) };
                    if status != SUCCESS {
                        unsafe { sys::mlx_array_free(out) };
                        return Err(anyhow!("multiply refused"));
                    }
                    Ok(vec![unsafe { Array::from_raw(out) }])
                };

                let (values, grads) = value_and_grad(square, &[0], &[Array::from_f32(3.0)])?;
                Ok((values[0].item_f32()?, grads[0].item_f32()?))
            })
            .expect("the runtime should let this through");

        assert_eq!(answer, (9.0, 6.0));
    }

    /// A closure that fails reports its own error rather than a generic one,
    /// which is the whole reason the parking slot exists.
    #[test]
    fn a_closure_that_fails_says_what_it_was() {
        let outcome = runtime::runtime().execute(|| {
            let refuses =
                |_: &[Array]| -> Result<Vec<Array>> { Err(anyhow!("the objective gave up")) };
            match value_and_grad(refuses, &[0], &[Array::from_f32(1.0)]) {
                Ok(_) => Err(anyhow!("it should not have succeeded")),
                Err(error) => Ok(error.to_string()),
            }
        });

        assert!(
            outcome.as_ref().is_ok_and(|said| said.contains("the objective gave up")),
            "{outcome:?}"
        );
    }

    /// A panic is contained rather than unwinding into C++.
    #[test]
    fn a_closure_that_panics_does_not_cross_the_boundary() {
        let outcome = runtime::runtime().execute(|| {
            let panics = |_: &[Array]| -> Result<Vec<Array>> { panic!("inside the closure") };
            match value_and_grad(panics, &[0], &[Array::from_f32(1.0)]) {
                Ok(_) => Err(anyhow!("it should not have succeeded")),
                Err(error) => Ok(error.to_string()),
            }
        });

        assert!(outcome.as_ref().is_ok_and(|said| said.contains("panicked")), "{outcome:?}");
    }
}
